#!/bin/bash
# Add a new host to the SentientHome Master
# Oliver Ratzesberger
# MIT License

usage()
{
  cat << EOF
usage: $0 [options]

Initial setup of the SentientHome Master

OPTIONS:
  --help|-h         Show this message
  --force|-f        Force generation of new keys. Replace existing
  --debug|-d        Debug mode


EOF
  exit 1
}

log()
{
  # Common logging format use in place of echo when possible
  me=`basename "$0"`

  echo `date +%Y%m%d%H%M%S%3N` "("$me")" "$1" "$2" "$3" "$4" "$5"
}

header()
{
  log SentientHome
  log
  log "Module:         " `basename "$0"`
  log "Path:           " "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  log "Host:           " `uname -n`
  log "OS:             " `uname -o`
  log "Kernel-Name:    " `uname -s`
  log "Kernel-Release: " `uname -r`
  log "Kernel-Version: " `uname -v`
  log "Machine:        " `uname -m`
  log "Processor:      " `uname -p`
  log "Platform:       " `uname -i`
  log
  log "git Version:    " `git --version`
  log
  log "git Revision:   " `git describe --tags --always HEAD`
  log "git Dirty:      " `git status --porcelain`
  log
}

# Start by logging environment info
header

# Default settings
DEBUG=0
FORCE=0

# translate long options to short
for arg
do
  delim=""
  case "${arg}" in
    --help) args="${args}-h ";;
    --force) args="${args}-f ";;
    --debug) args="${args}-d ";;
    # pass through anything else
    *) [[ "${arg:0:1}" == "-" ]] || delim="\""
      args="${args}${delim}${arg}${delim} ";;
  esac
done
# reset the translated args
eval set -- "$args"
# now we can process with getopt
while getopts "hfd" opt; do
  case $opt in
    h)  usage ;;
    f)  FORCE=1 ;;
    d)  DEBUG=1 ;;
    \?) usage ;;
    :)
      echo "Option -$OPTARG requires an argument\n"
      usage
    ;;
  esac
done
shift $((OPTIND -1))

if [ $DEBUG -eq 1 ]; then
  set -x
  OPT_OUTPUT="/dev/stdout"
else
  OPT_OUTPUT="/dev/null"
fi

# Install dependencies
log "Installing expect dependecy ..."
apt-get -y install expect 1>$OPT_OUTPUT

if [ $? -ne 0 ]; then
  log "👎  Error installing expect."
  exit 2
fi

if [ $FORCE -eq 1 ]; then
  RESPONSE="y"
else
  RESPONSE="n"
fi

KEYFILE=/root/.ssh/id_rsa
# Generating ssh key pair
log "Generating ssh key pair $KEYFILE ..."

expect 1>$OPT_OUTPUT << EOF
  set timeout 60
  spawn ssh-keygen -t rsa -b 4096 -q -P "" -f $KEYFILE

  expect {
    timeout {
      exit 2
    }
    "Overwrite (y/n)?" {
      send $RESPONSE
      send "\r"
      expect {
        timeout {
          exit 2
        }
      }
    }
    eof
  }
EOF

if [ $? -eq 2 ]; then
  log "👎  Key generation timed out. Try again or lower bits"
  exit 3
elif [ $? -ne 0 ]; then
  log "👎  Error generating key pair $KEYFILE"
  exit 4
fi

# Now lets install ansible

if [ $? -eq 0 ]; then
  log "🍺  Finished."
else
  log "👎  Someting went wrong."
fi
