#!/bin/bash
# Add a new host to the SentientHome Master
# Oliver Ratzesberger
# MIT License

# Setup logger limit to last 10 runs
LOGDIR=/tmp
LOGFILE="$LOGDIR/`basename $0`.`date +%Y%m%d%H%M%S`.log"
exec &> >(tee -a $LOGFILE)
( cd /tmp && rm -f $(ls -1t $LOGDIR/`basename $0`* | tail -n +10) )

# Default settings
OLD_PASSWD="hypriot"
DEBUG=0

# As we are working with sym links we also need to know the real path to here
REALPATH=`realpath ${BASH_SOURCE[0]}`
REALDIR=`dirname "$REALPATH"`
THIS=`basename "$0"`

usage()
{
  cat << EOF
usage: $0 [options] hostname-of-rpi

Add a newly created host to the SentientHome Master

OPTIONS:
  --help|-h         Show this message
  --newpassword|-n  Set new root password for host
  --oldpassword|-o  Existing root password for new host default=hypriot
  --debug|-d        Debug mode

EOF
  exit 1
}

log()
{
  # Common logging format use in place of echo when possible
  echo `date +%Y%m%d%H%M%S%3N` "("$THIS")" "$1" "$2" "$3" "$4" "$5"
}

header()
{
  log SentientHome
  log
  log "Version:        " "$( cd $REALDIR && git describe --tags --always HEAD )"
  log "Dirty Files:    " "$( cd $REALDIR && git status --porcelain )"
  log
  log "Module:         " $THIS
  log "Path:           " "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  log "Realpath:       " $REALDIR
  log "Logfile:        " $LOGFILE
  log "Host:           " `uname -n`
  log "OS:             " `uname -o`
  log "Kernel-Name:    " `uname -s`
  log "Kernel-Release: " `uname -r`
  log "Kernel-Version: " `uname -v`
  log "Machine:        " `uname -m`
  log "Processor:      " `uname -p`
  log "Platform:       " `uname -i`
  log
  log "apt-get:        " `apt-get --version`
  log "git:            " `git --version`
  log "parted:         " `parted --version`
  log "pip:            " `pip --version`
  log "python:         " $( python --version 2>&1 )
  log
}

# translate long options to short
for arg
do
  delim=""
  case "${arg}" in
    --help) args="${args}-h ";;
    --newpassword) args="${args}-n ";;
    --oldpassword) args="${args}-o ";;
    --debug) args="${args}-d ";;
    # pass through anything else
    *) [[ "${arg:0:1}" == "-" ]] || delim="\""
      args="${args}${delim}${arg}${delim} ";;
  esac
done
# reset the translated args
eval set -- "$args"
# now we can process with getopt
while getopts "hdn:o:" opt; do
  case $opt in
    h)  usage ;;
    n)  NEW_PASSWD=$OPTARG ;;
    o)  OLD_PASSWD=$OPTARG ;;
    d)  DEBUG=1 ;;
    \?) usage ;;
    :)
      echo "Option -$OPTARG requires an argument\n"
      usage
    ;;
  esac
done
shift $((OPTIND -1))

# Start by logging environment info
header

if [ $DEBUG -eq 1 ]; then
  set -x
  OPT_OUTPUT="/dev/stdout"
else
  OPT_OUTPUT="/dev/null"
fi

HOST=$1

if [ -z "$HOST" ]; then
  log "No host specified.\n"
  usage
fi

HOST_DOMAIN="${HOST##*.}"
HOST_NAME="${HOST%.*}"

function getip() { (traceroute $1 2>&1 | head -n 1 | cut -d\( -f 2 | cut -d\) -f 1) }
HOST_IP=$(getip ${HOST_NAME}.local)

if [ $? -eq 0 ]; then
  log "$1 found at $HOST_IP."
else
  log "$1 could not be located in network."
  exit 2
fi

log "Removing any existing host keys for $HOST_NAME and $HOST_IP ..."
ssh-keygen -R $HOST_IP &>$OPT_OUTPUT
ssh-keygen -R $HOST_NAME &>$OPT_OUTPUT

log "Copying public key to host $HOST_IP ..."

expect 1>$OPT_OUTPUT << EOF
  spawn ssh-copy-id -oStrictHostKeyChecking=no -oCheckHostIP=no root@${HOST_IP}

  expect {
    timeout {
      exit 2
    }
    "password:" {
      send "$OLD_PASSWD\r"
      expect {
        timeout {
          exit 2
        }
        "Permission denied" {
          exit 3
        }
      }
    }
    eof
  }
EOF

if [ $? -eq 3 ]; then
  log "👎  Incorrect host password."
  exit 3
elif [ $? -eq 2 ]; then
  log "👎  Key copy timed out."
  exit 2
fi

if [ -n $NEW_PASSWD ]; then
  log "Changeing password for root@${HOST_IP} ..."
ssh root@$HOST_IP passwd &>$OPT_OUTPUT << EOF
$NEW_PASSWD
$NEW_PASSWD
EOF
fi

if [ $? -eq 0 ]; then
  log "🍺  Finished."
else
  log "👎  Someting went wrong."
fi
